service: voice-memo-api

provider:
  name: aws
  stage: api
  runtime: nodejs12.x
  environment:
    bucket_name: ${file(./serverless-config.yml):bucket}

functions:
  getAudios:
    handler: handler.hello
    memorySize: 128
    events:
      - http:
          method: get
          path: /audio

  saveAudio:
    handler: src/routes/audio/set.run
    memorySize: 128
    events:
      - http:
          method: post
          path: /audio

custom:
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-offline
